# =========================
#   Projet SonarCloud
# =========================
# ⚠️ Adapte ces 2 lignes avec ce que tu as dans SonarCloud
sonar.projectKey=JTR220_symfony_bloc3
sonar.organization=jtr220

sonar.projectName=symfony_bloc3
sonar.projectVersion=1.0

# =========================
#   Source à analyser
# =========================
# On part de la racine du repo
sonar.sources=.

# On NE GARDE que le code applicatif dans src/
# -> tout le reste (docs, .github, etc.) est ignoré
sonar.inclusions=src/**

# Si jamais tu as un dossier vendor, var, etc., ils seront
# déjà exclus par l'inclusion, mais on peut être explicite :
sonar.exclusions=vendor/**,var/**,node_modules/**,public/**,config/**,tests/**

# (optionnel) Encodage des fichiers
sonar.sourceEncoding=UTF-8

# (optionnel) Si un jour tu ajoutes la couverture PHPUnit :
#sonar.php.coverage.reportPaths=var/coverage/coverage.xml
