# Identifiants (À récupérer sur SonarCloud comme tout à l'heure)
sonar.projectKey=JTR220_symfony_bloc3
sonar.organization=jtr220

# -----------------------------------------------------------------
# LE NETTOYAGE (C'est ici que tu retires les fichiers inutiles)
# -----------------------------------------------------------------
# On garde uniquement le code source (src)
sonar.sources=src

# LISTE D'EXCLUSION (Les fichiers à ne PAS scanner)
# vendor/** -> Les bibliothèques externes (ce n'est pas ton code)
# var/** -> Le cache et les logs Symfony
# config/** -> La configuration (souvent des faux positifs)
# public/** -> Les assets (images, css compilé)
# migrations/** -> Les fichiers SQL générés automatiquement
# bin/** -> Les exécutables
sonar.exclusions=vendor/**,var/**,config/**,public/**,migrations/**,bin/**

# Encodage
sonar.sourceEncoding=UTF-8